# Generated by Django 4.2.3 on 2023-08-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameRoom', '0006_player_is_assigned_location_player_is_assigned_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_assigned_location',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_assigned_role',
        ),
    ]
