# Generated by Django 4.2.3 on 2023-09-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameRoom', '0007_remove_player_is_assigned_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='player_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
