# Generated by Django 4.2.3 on 2023-09-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameRoom', '0008_alter_gameroom_player_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='is_game_started',
            field=models.BooleanField(default=False),
        ),
    ]
