# Generated by Django 4.2.3 on 2023-09-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameRoom', '0010_player_is_ready'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
