# Generated by Django 4.2.3 on 2023-07-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_profile_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_sent_at',
        ),
    ]
