# Generated by Django 4.2.3 on 2023-07-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_remove_profile_is_email_verified_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
