"""
Django settings for MafiaWebsite project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@3c25l29hzhu$811**&-lr955g-m49e6d0*)td#9#g6#ba%w$#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['www.mafiawebsite.xyz', '146.190.48.255', 'mafiawebsite.xyz']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'daphne',
    'django.contrib.staticfiles',
    'django_extensions',

    # my apps
    'mainpage',
    'GameRoom',
    'game',
    # alauth apps
    'django.contrib.messages',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'MafiaWebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MafiaWebsite.wsgi.application'
ASGI_APPLICATION = 'MafiaWebsite.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/'  # Jūsu vēlamais pāradresācijas URL pēc pieslēgšanās

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '610028372985-ijsc0ip2r7bhvh3u07lb1iiupsno33rm.apps.googleusercontent.com',
            'secret': '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',
            'key': '',
            'redirect_uri': 'http://localhost:8000/accounts/google/login/callback/'
        },
        'SCOPE': ['profile', 'email'],
    },
   'discord': {
        'APP': {
            'client_id': '1186998057536077888',
            'secret': 'Jūsu_Discord_Client_Secret',
        }
    }
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-en'

TIME_ZONE = 'Europe/Riga'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/home/urban/MafiaWebsite/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# jazzmitn settings(admin page)

JAZZMIN_SETTINGS = {
    'site_title': 'Mafia',
    'site_header': 'Game',
    'site_logo': '/mainpage/img/Logo.png',
    'welcome_sign': 'Welcome to Mafia',
    'show_sidebar': True,
    'navigation_expanded': True,
    'hide_apps': ["""'sites'"""],
    'show_ui_builder': False,
    'topmenu_links': [],
    'usermenu_links': [],
    'theme': 'home',
    'icons': {
        'app.Model': 'fas fa-icon',
        'auth.User': 'fas fa-user',
        'gameroom.GameRoom': 'fas fa-door-open',
        'gameroom.Player': 'fas fa-users',
        'game.role': 'fas fa-star',
        'game.location': 'fas fa-map-marker',
        'mainpage.Profile': 'fas fa-id-card',

    },
}

SITE_ID = 2
SOCIALACCOUNT_LOGIN_ON_GET = True


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.privateemail.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'team@mafiawebsite.xyz'
EMAIL_HOST_PASSWORD = 'Edvards!@#123'
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = 'WebsiteTitle <team@mafiawebsite.xyz>'

try:
    from MafiaWebsite.local_settings import *
except ImportError:
    pass