# Generated by Django 4.2.3 on 2023-07-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameRoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='max_players',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='player_count',
            field=models.IntegerField(default=0),
        ),
    ]
