# Generated by Django 4.2.3 on 2023-07-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameRoom', '0002_gameroom_max_players_alter_gameroom_player_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
