# Generated by Django 4.2.3 on 2023-08-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('GameRoom', '0004_remove_gameroom_is_owner_player_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.location'),
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players_in_game', to='game.role'),
        ),
    ]
