# Generated by Django 4.2.3 on 2023-09-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameRoom', '0009_gameroom_is_game_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
