# Generated by Django 4.2.3 on 2023-09-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameRoom', '0011_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='ready_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
